apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: yeseulhong/grass-diary:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: JWT_ACCESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_ACCESS_SECRET_KEY
            - name: JWT_REFRESH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_REFRESH_SECRET_KEY
            - name: DB_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_SERVER_URL
            - name: DB_USER_ID
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER_ID
            - name: DB_USER_PW
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER_PW
            - name: S3_ACCESS_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: S3_ACCESS_PUBLIC_KEY
            - name: S3_ACCESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: S3_ACCESS_SECRET_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: S3_BUCKET_NAME

